### ISSUE TITLE
Missing Java version of Rotate Image

### ISSUE THREAD

**Issue by syedareehaquasar** [KhushbooGoel01/Top-Interview-Questions--Leetcode#2]
There should be a java version for rotate image problems.

**Comment by syedareehaquasar** [comment]
I want to work on this issue @KhushbooGoel01. Please assign this to me.

**Comment by KhushbooGoel01** [comment]
> I want to work on this issue @KhushbooGoel01. Please assign this to me.

Yes Rheeha! go ahead.
